/** @file ipc.h
@author Roger Bongers
@date May 27 2015
@brief IPC common operations and values.
@details Functions and values for processing ipc_t.
@see sem.h shm.h
**/
#include <stdlib.h>
#include <sys/ipc.h>

#include <err.h>
#include <str.h>
#include <file.h>

/* ------------------------- START OF GUARD BLOCK ------------------------- */
#ifndef MM_IPC
#define MM_IPC
/**
@brief The flags used to define the permissions of a new IPC object.
@details IPC_CREAT and IPC_EXCL are often used as IPC flags, but here they are
disabled by many functions that use an ipc_t and re-enabled when necessary.
@see ipc_t
**/
enum IPC_FLAGS {
    IPC_USR_R = 0400,
    IPC_USR_W = 0200,
    IPC_GRP_R =  040,
    IPC_GRP_W =  020,
    IPC_OTH_R =   04,
    IPC_OTH_W =   02,
};

/**
@brief Contains information for creating IPC objects.
@see shm_t sem_t
**/
typedef struct
{
    int   flags; //!< The permissions of the IPC object.
    int   proj_id; //!< A semi unique program value used to generate keys.
    char* path; //!< The path of a file used to generate keys.
    key_t key; //!< A shared key between programs generated by agreed values.
} ipc_t;

/**
@brief The function to use to generate keys. ipc_gen_key_ftok() by default.
@param _path The name of the file to generate the key from.
@param _proj_id An agreed upon value used to generate a unique key.
@return Upon success, returns the key.
<br> Upon failure, returns -1, prints errors if necessary, and sets #err_num.
@beg{Errors}
@ent{_EPTRNULL, \b _path was NULL.}
@ent{_ESTREMPTY, \b _path begins with a '\0' character.}
@ent{_ESYSTEM, Error producing the key.}
@end
**/
extern key_t (*ipc_gen_key) (char* _path, int _proj_id);
#endif
/* -------------------------- END OF GUARD BLOCK -------------------------- */


/**
@brief Allocates a new ipc_t and sets all its values to 0 or NULL.
@return Upon success, returns a pointer to the new ipc_t.
<br> Upon failure, returns NULL, prints errors if necessary, and sets #err_num.
@beg{Errors}
@ent{_EALLOC, Unable to allocate memory.}
@end
**/
ipc_t* ipc_t_new (void);
/**
@brief
**/
int ipc_t_set
(ipc_t** _ipc, int _flags, int _proj_id, char* _path, key_t _key);
/**
@brief
**/
int ipc_t_from_path (ipc_t** _ipc, char* _root, char* _sub);
/**
@brief
**/
void ipc_t_del (ipc_t** _ipc);
/**
@brief
**/
char* ipc_gen_path (char* _root, char* _sub);
/**
@brief
**/
key_t ipc_gen_key_ftok (char* _path, int _proj_id);
